min_players: 6
max_players: 12

waiting_delay: 20
pre_game_countdown: 60
protection_countdown: 30
ingame_countdown: 1800
tracker_countdown: 1200
post_game_countdown: 20

inventory_sorting_name: "&cInventarsortierung &7(Rechtsklick)"
tracker_name: "&6Tracker"

tablist_header: "Header"
tablist_footer: "Footer"

remaining_on_quit: False