name: AuraClassic
version: 1.0.0
description: A simple Aura Classic plugin
main: net.rebux.auraclassic.AuraClassic
commands:
  start:
    usage: /start
    permission: aura.start
  stats:
    usage: /stats <player>