name: AuraClassic
version: 1.0.0
description: A simple Aura Classic plugin
main: net.rebux.auraclassic.AuraClassic
commands:
  setspawn:
    usage: /setspawn <lobby/map>
    permission: aura.setspawn
  start:
    usage: /start
    permission: aura.start
  stats:
    usage: /stats <player>
  statsall:
    usage: /statsall <player>
  statsd:
    usage: /statsd <days> <player>